    location = /auth_check.php {
        try_files $uri =404;
        fastcgi_pass  unix:/tmp/php-cgi-73.sock;
        fastcgi_index index.php;
        include fastcgi.conf;
        include pathinfo.conf;
        fastcgi_read_timeout 60s;
        fastcgi_send_timeout 60s;
    }
